### ISSUE TITLE
Suspicious logic in shiftarg_lon and shiftarg_lat

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/pystare#71]
The spatial.shiftarg_*() routines seem like stubs. The docstring says they're for keeping the argument on the right sheet, but neglect the negative bound.

Also, shiftarg_lat() makes no sense to me at all. As currently written shiftarg_lat(91)=-89. I don't know why an increment at the north pole should map to the vicinity of opposite pole. A more appropriate mapping would change both lon and lat.

https://github.com/SpatioTemporal/pystare/blob/0aeec6965d5f611202d94b2bf7e47e98c1487bca/pystare/spatial.py#L861-L877

**Comment by NiklasPhabian** [comment]
ha! I always was suspicious about this guy. Had to dig deep to find where he came from ... it was in v0.9 of the STARE library when pystare was still part of it. Good old legacy ... https://github.com/SpatioTemporal/STARE/commit/54d82d8d0a876b76be82d76b53f3b586d842e7c8 
I will replace (and rename) him.

**Comment by NiklasPhabian** [comment]
OK. This is generally tricky though. 

When we talk about longitudes, it is valid to conceptually have them go from 0 to 360 or alternatively from -180 to +180. It is therefore justified to introduce logic that forces longitudes to one schema or the other. Note that the logic in place does exactly that. Accidentally it also converts values that are larger than 360 and wraps them back around the globe rather than throwing a ValueError. It also quietly accepts values of less than -180 instead of throwing a value Error. We should therefore either accept values from -inf to inf and force them to the [-180, +180] schema or only accept values from [-180 to 360].  

When we talk about latitudes, it is not completely obvious what a value outside of [-90, +90] is even supposed to mean. Do we really want to wrap around the pole or is this just always nonsensical and should be caught as an ValueError. I am inclined to say yes to the latter. Note that cartopy also is only concerned with converting the longitudes.

https://github.com/SciTools/cartopy/blob/f187916d69fa922beba53f2593ccfc3676374e4c/lib/cartopy/crs.py#L395-L398

**Comment by NiklasPhabian** [comment]
strengthening my case; PostGIS has a function ```ST_Shift_Longutide()``` https://postgis.net/docs/ST_Shift_Longitude.html, but no ```ST_Shift_Latitude()```
